image:
  repository: harbor.apps.c6.numerique-interieur.com/mi-certifdamjanlab1/java-demo
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "master"

ingress:
  host: damjan-certif-integ.dev.numerique-interieur.com
